### PR TITLE
Version catalogs

### PR DESCRIPTION
**Pull request by imashnake0**
Removed the `buildSrc` module [in favour](https://twitter.com/JakeWharton/status/1491052851887755266?s=20&t=lvVbE1f9lEhYPYqaO0FIFg) of [version catalogs](https://docs.gradle.org/current/userguide/platforms.html).

**Summary of changes:**
1. Created the `libs` catalog: `gradle/libs.versions.toml`.
2. Migrated all build files.
3. Purged `buildSrc`.

**Note:** I'd like to briefly review this first before merging, hence the draft PR.

### CODE REVIEW

**Comment by imashnake0** [comment]
@raamcosta Let me know if there's anything you'd like for me to change.

**Comment by raamcosta** [comment]
Hi @imashnake0!

Thank you a lot for this, I've been wanting to do it myself!

It looks perfect, there is just one small issue 😅: we currently have 3 active branches, one for compose 1.1, one for compose 1.2 and one for compose 1.3 (the main branch). The way they work is that compose 1.2 branch contains all that compose 1.1 does plus some changes related with versions (or new features for example that are only possible on 1.2) and 1.3 contains all that 1.2 does plus versions stuff.

So for me to accept this, we should make sure that we do it also for compose-1.1 branch, then merge 1.1 into 1.2 and apply new changes then merge that into 1.3 (main) and apply new changes (the ones in this PR).

It's really unfair of me to ask you to do this, but I'll wait for your answer, if it's too much hassle, let me know I can definitely do it myself 🙂

**Comment by imashnake0** [comment]
No worries, I'll change the versions to match the ones in `compose-1.1` later today and change the target branch to it.

**Comment by imashnake0** [comment]
#214 has changes for `compose-1.1`.

**Comment by imashnake0** [comment]
Resolved in #214, #215, and #218.

**Pull request closed without merging**
