### PR TITLE
NavArgs toBundle method generate

### PR DESCRIPTION
**Pull request by way-kis**
- NavArgs toBundle method code generated
#303

### CODE REVIEW

**Comment by raamcosta** [comment]
Hey @way-kis 

Thanks for this!

It's kind of difficult to parse what is actual change and what is just code formatting. Maybe you could not do auto-formatting here as I'm not really following any auto-formatter since we have lots of special cases in this class.

Besides this, I believe generating a toBundle extension function for each type of NavArgs class will be better to not pollute the DestinationSpec more and also it will lead to better code on caller site:

`someNavArgs.toBundle()`

**Comment by raamcosta** [comment]
Hey @way-kis !

Do you have examples of usage with latest changes? My idea was to really move the extensions out of Destination and DestinationSpec. You can check the `NavArgsGetters.kt` generated file for a similar thing to what I was thinking about.

**Comment by way-kis** [comment]
example code 
`
data class SuvPageActivityNavArgs(
    val route: String,
    val startDestinationIndex: Int = 0,
    val bundle: Bundle = Bundle()
) {
    companion object {
        fun factory(
            graph: NavGraph,
            destination: DirectionDestination? = null,
            bundle: Bundle = Bundle()
        ) = SuvPageActivityNavArgs(
            route = graph.route,
            startDestinationIndex = destination?.let {
                graph.destinations.indexOf(it)
            } ?: 0,
            bundle = bundle
        )
    }
}

private fun SuvPageActivityNavArgs.findByRouteName(): NavGraph = when (route) {
    NavGraphs.sample.route -> {
        NavGraphs.sample
    }
    else -> {
        if (BuildConfig.DEBUG) {
            error("NotFound graph name!")
        }
        NavGraphs.root
    }
}
@ActivityDestination(navArgsDelegate = SuvPageActivityNavArgs::class)
@AndroidEntryPoint
class SubPageActivity : ComponentActivity() {
    private val args by lazy { SubPageActivityDestination.argsFrom(intent) }
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        val graph = args.findByRouteName()
        intent.putExtras(args.bundle)
        val startRoute = when {
            args.startDestinationIndex >= 0 -> {
                graph.destinations[args.startDestinationIndex]
            }
            BuildConfig.DEBUG -> {
                error("startRute No Include Graph")
            }
            else -> {
                graph.startRoute
            }
        }

        setContent {
            SampleTheme {
                GraphScreenContainer(
                    graph = graph,
                    startRoute = startRoute,
                    topBar = { navController, typedDestination, navBackStackEntry ->
                        TopBar(
                            navController = navController,
                            destination = typedDestination,
                            navBackStackEntry = navBackStackEntry
                        )
                    },
                    manualComposableCallsBuilder = {
                        sampleScreen(args)
                    }
                )
            }
        }
    }
}


fun ManualComposableCallsBuilder.sampleScreen(args: SuvPageActivityNavArgs) {
    composable(destination = SampleScreenDestination) {
        val argument = SampleScreenDestination.argsFrom(args.bundle)
        SampleScreen(key = argument.key)
    }
}

@SampleNavGraph(true)
@Destination
@Composable
fun SampleScreen(
   key: String = "",
){
}

`

**Comment by way-kis** [comment]
> Hey @way-kis !
> 
> Do you have examples of usage with latest changes? My idea was to really move the extensions out of Destination and DestinationSpec. You can check the `NavArgsGetters.kt` generated file for a similar thing to what I was thinking about.

feedback apply. plz check

**Pull request closed without merging**
